version: "2.3"
services:
  web:
    environment:
          - NODE_ENV=${NODE_ENV}
    build:
      context: .
    ports:
      - "80:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.6
    volumes:
      - /Users/johnsurface/Documents/data/db:/data/db
    ports:
      - "27017:27017"